name: 'Dismount RAM Disk (Windows)'
description: 'A cleanup action for high performance CI/CD storage using a RAM-backed disk on Windows.'
author: "chad-golden"
branding:
  icon: hard-drive
  color: red
inputs:
  drive-letter:
    type: string
    description: 'The drive letter to dismount for the mounted RAM disk. Do not include the (:). Default is R'
    default: R
runs:
  using: 'composite'
  steps:
    - shell: pwsh
      env:
        DRIVE_LETTER: ${{ inputs.drive-letter }}
      run: ${{ github.action_path }}/../scripts/dismount.ps1